"""Update product model with default values and fix barcode_type

Revision ID: 779d6579dc35
Revises: 46c36e0cea4d
Create Date: 2025-03-20 19:34:07.544558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '779d6579dc35'
down_revision = '46c36e0cea4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)

    # ### end Alembic commands ###
