"""Add icon field to categories table

Revision ID: bb7f1e7e24f9
Revises: 766dc6f5082d
Create Date: 2025-03-09 21:40:57.253157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb7f1e7e24f9'
down_revision = '766dc6f5082d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
